services:
  frontend:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    container_name: chatboq-frontend
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      NODE_ENV: production