export const CHAT_EVENTS = {
  typing: 'typing',
  edit_message: 'edit_message',
  receive_message: 'receive_message',
  receive_typing: 'receive_typing',
  stop_typing: 'stop_typing',
  message_seen: 'message_seen',
  join_conversation: 'join_conversation',
  customer_land: 'customer_land',
  message_notification: 'message_notification',
  agent_connected: 'agent_connected',
  agent_disconnected: 'agent_disconnected',
  customer_conversation_join: 'customer_conversation_join',
  agent_conversation_join: 'agent_conversation_join',
  customer_conversation_leave: 'customer_conversation_leave',
  agent_conversation_leave: 'agent_conversation_leave',
  customer_disconnected: 'customer_disconnected',
  resolved_conversation: 'resolved_conversation',
  unresolve_conversation: 'unresolve_conversation',
  leave_conversation: 'leave_conversation',
  customer_email_update: 'customer_email_update',
};
